ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - hosts:
        - "lms-micro-app-227cdc86.nip.io"
  hosts:
    - host: "lms-micro-app-227cdc86.nip.io"
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: lms-micro-frontend-service
              port:
                number: 5173
        - path: /gateway/
          pathType: Prefix
          backend:
            service:
              name: lms-micro-gateway-service
              port:
                number: 4000